
name: Build and Deploy Pages

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Or your preferred Node.js version

    

    - name: Run page generation script
      run: node generate-pages.js

    - name: List generated files for debugging
      run: ls -R

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        # If you want to deploy to a specific branch (e.g., gh-pages), uncomment below
        # publish_branch: gh-pages
        # If you want to keep the history of gh-pages branch, uncomment below
        # keep_files: true
